import Account from "@/components/ui/account";

import Footer from "@/components/ui/footer";
import "@/styles/globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { User } from "../lib/schema";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const user: User = {
  firstName: "Jameel",
  lastName: "Ursonal",
  email: "baba@example.com",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Account user={user} />

        {children}
        <Footer />
      </body>
    </html>
  );
}
