import Account from "@/components/ui/account";

import InfoModal from "@/components/modals/info-modal";
import { ThemeProvider } from "@/components/threme-provider";
import Footer from "@/components/ui/footer";
import { ModeToggle } from "@/components/ui/theme-mode-button";
import { inter } from "@/styles/fonts";
import "@/styles/globals.css";
import { UserProvider } from "@auth0/nextjs-auth0/client";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <UserProvider>
        <body className={inter.className}>
          <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          >
            <div className="flex flex-col items-center gap-6 fixed top-7 right-7">
              <Account />
              <ModeToggle />
              <InfoModal />
            </div>
            {children}
            <Footer />
          </ThemeProvider>
        </body>
      </UserProvider>
    </html>
  );
}
